---
- name: list OSD journals
  shell:
    ls /var/lib/ceph/osd/*/journal -la > ceph_journals_{{ hostvars['localhost'].checkup_timestamp }}.txt

- name: fetch OSD journal list
  fetch:
    src: ceph_journals_{{ hostvars['localhost'].checkup_timestamp }}.txt
    dest: status

- name: get current SCSI state
  fetch:
    src: /proc/scsi/scsi
    dest: status
